server:
  ssh:
    port: 2222
    host_key: ""  # Set via SSH_HOST_KEY environment variable
  http:
    port: 80

domain:
  base: "p0rt.xyz"
  reservations_enabled: false  # Enable domain reservations for specific SSH keys

storage:
  type: "json"        # "json" or "redis"
  data_dir: "./data"  # Used for JSON storage
  
  # Redis configuration (when type: "redis")
  # redis_url: "redis://localhost:6379"
  # redis_password: ""
  # redis_db: 0