services:
  p0rt:
    build: .
    container_name: p0rt
    restart: unless-stopped
    ports:
      - "22:22"
      - "80:80"
    volumes:
      - ./ssh_host_key:/app/ssh_host_key:rw
      - ./authorized_keys.json:/app/authorized_keys.json:rw
      - ./data:/app/data:rw
    environment:
      - SSH_SERVER_PORT=22
      - HTTP_PORT=80
      - P0RT_OPEN_ACCESS=false
    # Nécessaire pour que setcap fonctionne
    security_opt:
      - no-new-privileges:false
    networks:
      - p0rt-net

networks:
  p0rt-net: