services:
  p0rt:
    build: .
    container_name: p0rt
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./ssh_host_key:/app/ssh_host_key:rw
      - ./authorized_keys.json:/app/authorized_keys.json:rw
      - ./data:/app/data:rw
    environment:
      - SSH_SERVER_PORT=${SSH_SERVER_PORT}
      - HTTP_PORT=${HTTP_PORT}
      - P0RT_OPEN_ACCESS=${P0RT_OPEN_ACCESS}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - DOMAIN_BASE=${DOMAIN_BASE}
      - P0RT_AUTHORIZED_KEYS=${P0RT_AUTHORIZED_KEYS}
      - P0RT_VERBOSE=${P0RT_VERBOSE}
    # Nécessaire pour que setcap fonctionne
    security_opt:
      - no-new-privileges:false
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: p0rt-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  redis-data: