services:
  p0rt:
    build: .
    container_name: p0rt
    restart: unless-stopped
    ports:
      - "22:22"
      - "80:80"
    volumes:
      - ./ssh_host_key:/app/ssh_host_key:rw
      - ./authorized_keys.json:/app/authorized_keys.json:rw
      - ./data:/app/data:rw
    environment:
      - SSH_SERVER_PORT=22
      - HTTP_PORT=80
      - P0RT_OPEN_ACCESS=false
      - REDIS_URL=redis://redis:6379
    # Nécessaire pour que setcap fonctionne
    security_opt:
      - no-new-privileges:false
    networks:
      - p0rt-net
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: p0rt-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - p0rt-net
    ports:
      - "6379:6379"

networks:
  p0rt-net:

volumes:
  redis-data: