version: '3.8'

services:
  p0rt:
    build: .
    container_name: p0rt
    restart: unless-stopped
    ports:
      - "22:22"
      - "80:80"
    volumes:
      - ./ssh_host_key:/app/ssh_host_key
      - ./authorized_keys.json:/app/authorized_keys.json
      - ./data:/app/data
    environment:
      - SSH_SERVER_PORT=22
      - HTTP_PORT=80
      - P0RT_OPEN_ACCESS=false
    networks:
      - p0rt-net

networks:
  p0rt-net: